'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Dominos.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BBQ_Dip_20170626() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BBQ_Dip-20170626", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BBQ_Sauce_20170613() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BBQ_Sauce_20170613", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cheese_and_tomato_20170704() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cheese-and-tomato-20170704", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cheese_and_tomato_20170704_large() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cheese-and-tomato-20170704-large", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ChicknMix_20170626() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChicknMix-20170626", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ChilliOil_20170626() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChilliOil-20170626", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property coca_cola_drink_20171123() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coca-cola-drink-20171123", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property coca_cola_zero_drink_20171123() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coca-cola-zero-drink-20171123", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Crust_C_ComponentImage_PizzaChef_Stack_Circle_1_en_Default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Crust.C_ComponentImage_PizzaChef.Stack.Circle.1_en_Default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Crust_C_ComponentImage_PizzaChef_Tray_en_Default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Crust.C_ComponentImage_PizzaChef.Tray_en_Default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Crust_H_ComponentImage_PizzaChef_Stack_Circle_1_en_Default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Crust.H_ComponentImage_PizzaChef.Stack.Circle.1_en_Default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Crust_H_ComponentImage_PizzaChef_Tray_en_Default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Crust.H_ComponentImage_PizzaChef.Tray_en_Default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Crust_P_ComponentImage_PizzaChef_Stack_Circle_1_en_Default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Crust.P_ComponentImage_PizzaChef.Stack.Circle.1_en_Default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Crust_P_ComponentImage_PizzaChef_Tray_en_Default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Crust.P_ComponentImage_PizzaChef.Tray_en_Default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Crust_T_ComponentImage_PizzaChef_Stack_Circle_1_en_Default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Crust.T_ComponentImage_PizzaChef.Stack.Circle.1_en_Default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Crust_T_ComponentImage_PizzaChef_Tray_en_Default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Crust.T_ComponentImage_PizzaChef.Tray_en_Default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property deluxe_20170704_large() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deluxe-20170704-large", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property diet_coke_drink_20171123() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("diet-coke-drink-20171123", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dips_Small_x4_20170626() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dips_Small_x4-20170626", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dominos_Own_Tomato_Sauce_20170613() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dominos_Own_Tomato_Sauce_20170613", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fanta_drink_20171123() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fanta-drink-20171123", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property farmhouse_20170704() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("farmhouse-20170704", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property farmhouse_20170704_large() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("farmhouse-20170704-large", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Franks_Dip_20170626() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Franks_Dip-20170626", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Garlic_Dip_20170626() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Garlic_Dip-20170626", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GarlicBread_20170626() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GarlicBread-20170626", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GarlicBread_201706261() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GarlicBread-201706261", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property large() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("large", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property meatzzapizza_20170704() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("meatzzapizza-20170704", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property meatzzapizza_20170704_large() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("meatzzapizza-20170704-large", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property medium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MeltinBalls_20170626() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MeltinBalls-20170626", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mighty_meaty_20170704() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mighty-meaty-20170704", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mighty_meaty_20170704_large() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mighty-meaty-20170704-large", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NL_Sauce_X_all_CircleLayer1Image_1275() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NL_Sauce.X_all_CircleLayer1Image_1275", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NL_Topping_B_all_CircleLayer1Image_1121() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NL_Topping.B_all_CircleLayer1Image_1121", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NL_Topping_B_all_CircleLayer2Image_1121() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NL_Topping.B_all_CircleLayer2Image_1121", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NL_Topping_B_all_CircleLayer3Image_1121() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NL_Topping.B_all_CircleLayer3Image_1121", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NL_Topping_K_all_CircleLayer3Image_1275() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NL_Topping.K_all_CircleLayer3Image_1275", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NL_Topping_K_all_TrayImage_1275() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NL_Topping.K_all_TrayImage_1275", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pepperonipassion_20170704() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pepperonipassion-20170704", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pepperonipassion_20170704_large() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pepperonipassion-20170704-large", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PizzaChef_Tray_Circle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PizzaChef-Tray-Circle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sauce_HBBSCComponentImagePizzaChef_Stack_Circle_1ENDefault19000101_011052() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sauce.HBBSCComponentImagePizzaChef.Stack.Circle.1ENDefault19000101_011052", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sauce_HBBSCComponentImagePizzaChef_TrayENDefault19000101_011053() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sauce.HBBSCComponentImagePizzaChef.TrayENDefault19000101_011053", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sauce_X_ComponentImage_PizzaChef_Tray_en_Default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sauce.X_ComponentImage_PizzaChef.Tray_en_Default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sauce_Xb_ComponentImage_PizzaChef_Stack_Circle_1_en_Default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sauce.Xb_ComponentImage_PizzaChef.Stack.Circle.1_en_Default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sauce_Xb_ComponentImage_PizzaChef_Tray_en_Default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sauce.Xb_ComponentImage_PizzaChef.Tray_en_Default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sauce_Xz_ComponentImage_PizzaChef_Stack_Circle_1_en_Default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sauce.Xz_ComponentImage_PizzaChef.Stack.Circle.1_en_Default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sauce_Xz_ComponentImage_PizzaChef_Tray_en_Default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sauce.Xz_ComponentImage_PizzaChef.Tray_en_Default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property smartwater_drink_20170704() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smartwater-drink-20170704", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sprite_drink_20171123() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sprite-drink-20171123", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sundried_Tomato_and_Garlic_Sauce_20170613() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sundried_Tomato_and_Garlic_Sauce_20170613", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tandoorihot_20170704_large() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tandoorihot-20170704-large", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property texasbbq_20170704() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("texasbbq-20170704", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property texasbbq_20170704_large() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("texasbbq-20170704-large", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Topping_B_ComponentImage_PizzaChef_Tray_en_Default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Topping.B_ComponentImage_PizzaChef.Tray_en_Default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Topping_F_ComponentImage_PizzaChef_Stack_Circle_1_en_Default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Topping.F_ComponentImage_PizzaChef.Stack.Circle.1_en_Default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Topping_F_ComponentImage_PizzaChef_Stack_Circle_2_en_Default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Topping.F_ComponentImage_PizzaChef.Stack.Circle.2_en_Default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Topping_F_ComponentImage_PizzaChef_Stack_Circle_3_en_Default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Topping.F_ComponentImage_PizzaChef.Stack.Circle.3_en_Default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Topping_F_ComponentImage_PizzaChef_Tray_en_Default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Topping.F_ComponentImage_PizzaChef.Tray_en_Default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Topping_V_ComponentImage_PizzaChef_Stack_Circle_1_en_Default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Topping.V_ComponentImage_PizzaChef.Stack.Circle.1_en_Default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Topping_V_ComponentImage_PizzaChef_Stack_Circle_2_en_Default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Topping.V_ComponentImage_PizzaChef.Stack.Circle.2_en_Default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Topping_V_ComponentImage_PizzaChef_Stack_Circle_3_en_Default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Topping.V_ComponentImage_PizzaChef.Stack.Circle.3_en_Default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Topping_V_ComponentImage_PizzaChef_Tray_en_Default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Topping.V_ComponentImage_PizzaChef.Tray_en_Default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tray_placeholder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tray-placeholder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Wedges_20170626() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wedges-20170626", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
